### ISSUE TITLE
I Am Facing 404 Not Found Issue

### ISSUE THREAD

**Issue by STRK-ND** [mitchmac/ServerlessWP#42]
![image](https://github.com/mitchmac/ServerlessWP/assets/50959267/48e24487-4076-497b-9556-2d41f15953fd)
 I am Facing this Issue on all page, The WordPress Dashboard Is Opening But In Dashboard I cant open the pages

**Comment by spectronp** [comment]
same issue here, but in my case it doesnt get back after some refreshes
