### ISSUE TITLE
How to change the database

### ISSUE THREAD

**Issue by guoyd233** [mitchmac/ServerlessWP#62]
Planetscale will discontinue its free plan in April. Is there a simple way to switch databases without resetting everything in WordPress? Thank you.

**Comment by hooopo** [comment]
TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy. 

https://docs.pingcap.com/tidbcloud/dev-guide-wordpress
