### ISSUE TITLE
Issue with Deployment on Vercel and Netlify Due to Incompatibility with Node.js Version 20.x

### ISSUE THREAD

**Issue by TomoyaKuroda** [mitchmac/ServerlessWP#64]
**Issue Description:**

During the deployment process on Vercel, I found that the default Node.js version (20.x) does not support the required functionality. This incompatibility is hindering the successful deployment of the application.

**Proposed Solution:**

To address this issue, I'd like to create a new pull request to include instructions for deploying ServerlessWP. These instructions should advise users to utilize Node.js version 18.x to ensure compatibility and successful deployment.

**Proposed Pull Request Content:**

```
## Deploying ServerlessWP

5. Please ensure that Node.js version 18.x is selected to deploy ServerlessWP.
```

**Additional Notes**

Downgrading version to 18.x is a temporal solution so we need to find a way to make this still work with Node.js 20.x.

**Comment by aldosch** [comment]
Created pull request #73 to solve this

**Comment by mitchmac** [comment]
Fix has been merged, thank you folks!
